version: '3'
services:
  fdroid:
    build:
      dockerfile: Dockerfile.fdroid
    volumes:
      - ./fdroid:/home/build/repo
    command: bash entrypoint.sh
    platform: linux/amd64

  debian:
    build:
      dockerfile: Dockerfile.debian
    volumes:
      - ./linux/debian:/home/build/repo
      - ./gpg-private-key.asc:/home/build/gpg-private-key.asc
    env_file:
      - .env
    command: bash entrypoint.sh
    platform: linux/amd64

  arch:
    build:
      dockerfile: Dockerfile.arch
    volumes:
      - ./linux/arch:/home/build/repo
      - ./gpg-private-key.asc:/home/build/gpg-private-key.asc
    env_file:
      - .env
    command: bash entrypoint.sh
    platform: linux/amd64
