FROM vineelsai/arch

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm -y go git cmake unzip curl wget base-devel libx11 libxft libxinerama

RUN useradd -ms /bin/bash build
RUN mkdir -p /home/build
USER build
WORKDIR /home/build

COPY scripts/entrypoint.arch.sh entrypoint.sh
