FROM vineelsai/ubuntu

RUN apt update
RUN apt upgrade -y
RUN apt install -y golang git ninja-build gettext cmake unzip curl wget file dpkg-dev libxinerama-dev fontconfig libxft-dev cargo libssl-dev just pandoc

RUN update-ca-certificates

RUN useradd -ms /bin/bash build
RUN mkdir -p /home/build
USER build
WORKDIR /home/build

COPY scripts/entrypoint.ubuntu.sh entrypoint.sh
