version: '3'
services:
  fdroid:
    build:
      dockerfile: Dockerfile.fdroid
      platforms:
        - linux/amd64
    volumes:
      - ./fdroid:/home/build/repo
    command: bash entrypoint.sh

  debian:
    build:
      dockerfile: Dockerfile.debian
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./linux/debian:/home/build/repo
      - ./gpg-private-key.asc:/home/build/gpg-private-key.asc
    env_file:
      - .env
    command: bash entrypoint.sh
    platform: linux/arm64

  arch:
    build:
      dockerfile: Dockerfile.arch
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./linux/arch:/home/build/repo
      - ./gpg-private-key.asc:/home/build/gpg-private-key.asc
    env_file:
      - .env
    command: bash entrypoint.sh
